<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.0.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Beer Suggestion  Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => 'thank-you.html',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'beer@depotbottombrewery.com',
		'to' => 'beer@depotbottombrewery.com'
	),
	'fields' => array(
		'custom_U1452' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Name\' is required.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Email\' is required.',
				'format' => 'Field \'Email\' has an invalid email.'
			)
		),
		'custom_U1447' => array(
			'order' => 3,
			'type' => 'string',
			'label' => ' Beer suggestion type',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U1743' => array(
			'order' => 5,
			'type' => 'checkbox',
			'label' => 'The submission of this suggestion does not mean Depot Bottom Brewery is held liable in brewing the suggestion submitted. Owners digression is used when brewing. I hereby agree to allow Depot Bottom Brewery to gain full rights of name and brewing idea',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'The submission of this suggestion does not mean Depot Bottom Brewery is held liable in brewing the suggestion submitted. Owners digression is used when brewing. I hereby agree to allow Depot Bottom Brewery to gain full rights of name and brewing idea\' is required.'
			)
		),
		'custom_U6202' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Beer suggested name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Beer suggested name\' is required.'
			)
		)
	)
);

process_form($form);
?>
